### ISSUE TITLE
TIMESTAMP_FORMAT

### ISSUE THREAD

**Issue by zonky2** [fiedsch/contao-4-backup-script#11]
wenn es zum Löschen bei PURGE_TIMESTAMP_FORMAT das selbe Format wie bei BACKUP_TIMESTAMP_FORMAT sein muss, warum dann zwei Eingaben?

als Fallback für Rückwärtskompatibilität, würde ich per Default 
PURGE_TIMESTAMP_FORMAT = BACKUP_TIMESTAMP_FORMAT machen es sei denn, bei PURGE_TIMESTAMP_FORMAT ist was individuelles eingetragen

**Comment by fiedsch** [comment]
Weil es nicht das gleiche Format haben muss!

Beispiel:

```bash
BACKUP_TIMESTAMP_FORMAT='%Y-%m-%d_%H_%M_%S'
```
gesetzt, weil mehr als ein Mal am Tag Backups gemacht werden sollen. Mit 
```bash
BACKUP_TIMESTAMP_FORMAT='%Y-%m-%d'
```
würde das zweite Backup ja das erste überschreiben.

Beim Löschen wird in 

```bash
PURGE_TIMESTAMP_FORMAT='%Y-%m-%d'
```
aber nur das Datum benötigt: lösche alle Backups vom angegebenen Datum.

Beide Parameter sind optional und als Standard wird `%Y-%m-%d` verwendet.
