### ISSUE TITLE
Reihenfolge der Verarbeitung ändern: erst löschen - dann erstellen

### ISSUE THREAD

**Issue by zonky2** [fiedsch/contao-4-backup-script#12]
Reihenfolge der Verarbeitung ändern: erst löschen - dann erstellen

... bei großen Backups inkl. /files könnte es zu Platzproblemen kommen - daher erst löschen, dann erstellen

**Comment by fiedsch** [comment]
Möchte ich eigentlich ungerne so machen:

* Wenn Du wegen einem Backup mehr in Platzprobleme läufst, hast Du m.E. sowieso gröbere Probleme.
* M.E. wichtiger: ich will alte Backups erst löschen, bevor das neue erfolgreich durchgelaufen ist.

TODO wäre hier natürlich noch: **prüfen wir an allen Stellen, ob die jeweilige Operation (*.tar erstellen, mysqldump etc. erfolgreich war und brechen ansonsten mit einem Fehlercode größer `0` ab.**


Wenn es unbedingt benötigt wird: in einem Skript, das das Backup-Skript aufruft prüfen, wieviel Plattenplatz noch frei ist (`df`), dann ggf. selbst löschen oder verschieben  (und im Backup-Skript evtl. `PURGE_AFTER_DAYS=0` setzen).

**Comment by zonky2** [comment]
> TODO wäre hier natürlich noch: prüfen wir an allen Stellen, ob die jeweilige Operation (*.tar erstellen, mysqldump etc. erfolgreich war und brechen ansonsten mit einem Fehlercode größer 0 ab.

klingt gut!
