### ISSUE TITLE
Ausgaben auf Konsole

### ISSUE THREAD

**Issue by zonky2** [fiedsch/contao-4-backup-script#13]
siehe auch 

* https://github.com/fiedsch/contao-4-backup-script/issues/9
* https://github.com/fiedsch/contao-4-backup-script/issues/8

Ich würde das `ls -lh ${TARGET_DIR}/${DUMP_NAME}_*` raus nehmen und dafür eine Ausgabe i.E. wie folgt machen:

```
Backup-Pfad: /pxyz/html/backup
Gelöschte Dateien:
myproject_2019-07-02.sql.gz
myproject_2019-07-02.tar.gz
myproject_2019-07-02.files.txt
Neues Backup:
myproject_2019-07-24.sql.gz
myproject_2019-07-24.tar.gz
myproject_2019-07-24.files.txt
Ordnergöße /backup: 5.45 GB
```

**Comment by fiedsch** [comment]
Siehe 201176142b304271ce98c510bc988f036cb41259

Ich halte es aber nicht für so sinnvoll, die Ordnergröße zu bestimmen und auszugeben, da hier auch andere Dateien liegen könnten, die mit dem Backup-Script nichts zu tun haben.

`Gelöschte Dateien` kann ich nicht ausgeben, da 

```bash
rm -f ${TARGET_DIR}/${DUMP_NAME}_${OLD}*
```
nur versucht, Dateien zu löschen, die auf das Muster passen würden. Falls es keine gibt, wird eine diesbezügliche Meldung mit `-f` unterdrückt. D.h. ich (das Script) weiß nicht, ob etwas gelöscht wurde). 

Das könnte man sicherlich herausfinden, allerdings sehe ich hier keinen großen Gewinn.
Als User will ich (aus meiner Sicht) nur sicher stellen, daß alte Backups irgendwann verschwinden, damit die Platte nicht voll läuft.

**Comment by zonky2** [comment]
im Grunde ging es mir darum, dass angezeigt wird, welches Backup-Set gerade erzeugt wurde - hier alle vorhandenen Backups aufzulisten ist für mich eher uninteressant... aber darüber kann man sicher "streiten"

**Comment by fiedsch** [comment]
> darüber kann man sicher "streiten"
Wohl wahr ;-). Ich persönlich finde es hilfreich, zu sehen welche (und damit auch in etwa wieviele) Backups momentan vorliegen.

**Comment by zonky2** [comment]
Alternativ wäre ein Flag `show_all` vs. `show_last` möglich

**Comment by fiedsch** [comment]
Ist mir persönlich zu viel, denn es ist ja ein Backup und kein Dateiverwaltungsskript.

Mein Setup auf Maschinen, auf denen ich mehrere Contao-Installationen habe (und Backups anfertige):

* Skript `backup-wrapper.sh` im cron job eingetragen.
* Im `backup-wrapper.sh` dann der Reihe nach der Aufruf der `main.sh` die ich jeweils nach dem zu sichernden Projekt benannt habe.
* Am Ende dieses Skripts würden m.E. individuelle Aktionen, Prüfungen oder Ausgaben  gut aufgehoben sein.

**Comment by zonky2** [comment]
o.k. - wenn es per Cron läuft, sieht man das ja eh nicht mehr...

**Comment by fiedsch** [comment]
Ich lasse mir den Output der cronjobs als E-Mail zuschicken. Die Mails lösche ich meist ungelesen, da sie nur meine Benachrichtigung für "cronjob ist gelaufen" sind. Bei Bedarf kann ich dann aber rein schauen und sehe, welche Backups (von wann und welcher Größe) ich habe. Daher  das `ls -l`.

**Comment by zonky2** [comment]
o.k.
