### ISSUE TITLE
Fehlermeldung bei Ausführung des Scriptes nach Neuinstallation 4.9 

### ISSUE THREAD

**Issue by mlwebworker** [fiedsch/contao-4-backup-script#16]
Nach dem ich ein Installation auf Contao 4.9.1 upgedatet habe bekomme ich bei All-Inkl. folgende 
Fehlermeldung:
18:18:09 ERROR     [console] Error thrown while running command "debug:container --parameter=database_port". Message: "syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)" ["exception" => ParseError { â€¦},"command" => "debug:container --parameter=database_port","message" => "syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)"]
    [41] => 
    [42] => In Configuration.php line 29:
    [43] => 
    [44] =>   syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_C
    [45] =>   ONST)
    [46] => 
    [47] => 
Das Update wurde als Parallelinstallation durchgeführt, deshalb musste ich die Pfade in der main.sh anpassen.
Irgenwie kann ich mir auf diese Fehlermeldung so gar keinen Reim machen.

**Comment by fiedsch** [comment]
Hallo Maren, 
der Fehler sieht für mich danach aus, als ob (im Skript) die falsche PHP-Version verwendet wird.
Was hast Du denn bei der Einstellung `PHP_CLI` (https://github.com/fiedsch/contao-4-backup-script/blob/master/main.sh#L15) stehen und was wird auf der Kommandozeile dafür ausgegeben?

**Comment by mlwebworker** [comment]
Ich habe 
PHP_CLI=php
und in der Konsole wird dafür 
PHP 7.4.2 (cli) (built: Feb  4 2020 13:21:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
ausgegeben
Ich habe aber gerade noch mit php73 getestet. Das ergibt auf der Konsole.
PHP 7.3.11-nmm1 (cli) (built: Nov 11 2019 09:16:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
Da läuft es.
Ich hatte beim Update und der Umstellung der PHP-Version auf PHP 7.4 bei der Konsole auch umgestellt, dass bei der Verwendung von "php" immer "php74" genutzt wird. Vorher war das "php73".
Danke für den Schubs in die richtige Richtung.

**Comment by mlwebworker** [comment]
Zu früh gefreut. Ich war im falschen Ordner bei meinem Test. Also Contao 4.8 läuft mit php73 und auch mit php (dahinter steckt PHP 7.4) hier ist für die Domain PHP 7.3 eingestellt. Contao 4.9 bringt nach wie vor obigen Fehler egal ob ich im Script php oder php73 nutze. Für diese Domain ist PHP 7.4 eingestellt.

**Comment by fiedsch** [comment]
Muss ich versuchen nachzustellen. Ich habe zwar bereits einige Contao 4.9.1 damit gesichert, aber die laufen noch alle mit PHP 7.3.

**Comment by fiedsch** [comment]
Gerade mit einer lokalen Installation ausprobiert:

Contao: 4.9.1

PHP: 

```
php -v
PHP 7.4.3 (cli) (built: Feb 20 2020 12:23:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```
Webserver läuft ebenfalls unter PHP 7.4

Das sollte also Deiner Konfiguration entsprechen. 

Funktioniert "leider" wie erwartet, d.h. ich kann Deinen Fehler nicht nachstellen.

Sagt der Fehler bei Dir noch etwas dazu, in welcher Datei der Fehler auftritt (`Configuration.php` gibt es viele verschiedene). Die einzige, die ich spontan gefunden habe, in der in Zeile `29` ein `?` steht wäre die `vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php` und dort dann die Zeile

```
protected ?string $proxiesTargetDir;
```

Das ist PHP 7.4 Code und einen Fehler könnte ich mir nur erklären, wenn versucht wird, das mit PHP 7.3 auszuführen.

**Comment by fiedsch** [comment]
Eine Idee für's Debuggen vielleicht noch: Das Problem tritt auf, wenn versucht wird, die Zugangsdaten zur Datenbank aus der Contao-Konfiguration auszulesen. Das passiert (am Beispiel Datenbank-User) letztlich mit 
```
php vendor/bin/contao-console debug:container --parameter=database_user
```
Die Ausgabe (mit dem Ergebnis `myusername`) sollte dann in etwa so aussehen:

```
$ php vendor/bin/contao-console debug:container --parameter=database_user
 --------------- ------- 
  Parameter       Value  
 --------------- ------- 
  database_user   myusername   
 --------------- ------- 
```

Kannst Du das vielleicht mal auf Deinem Server probieren?

**Comment by mlwebworker** [comment]
Der Befehl funktioniert. 
Ich werde die Fehlersuche wohl erst mal zurückstellen müssen. Ich bin ab morgen beim Agenturtag in Karlsruhe.

**Comment by mlwebworker** [comment]
Ich glaube ich hab ihn. Ich verstehe zwar nicht warum, aber wenn ich explizit php74 eingebe funktioniert es. Ich verstehe zwar nicht was der Unterschied ist, denn php -v auf der Konsole gibt ebenfall PHP 7.4 aus. Hatte ich nach einer Anleitung von All-Inkl auf der Konsole mit folgendem Befehl eingestellt:
ln -sfv /usr/bin/php74 /usr/bin/php
Der ganze Aufruf erfolgt ja bei All-Inkl. über ein PHP Script. Wer weiss... Ich muss ja auch nicht immer alles verstehen.

Bei der Fehlersuche ist mir aufgefallen, dass in Deiner Readme für All-Inkl. noch fehlt:

PURGE_AFTER_DAYS=0

weil der Befehl zum Löschen auch nicht freigegeben ist. 
Löschung kann dann über Tools->Webspacebereinihung automatisiert werden

**Comment by fiedsch** [comment]
> Ich bin ab morgen beim Agenturtag in Karlsruhe.

Dann erstmal viel Spaß da.

> wenn ich explizit php74 eingebe funktioniert es. 

Dann schließe ich das Ticket einstweilen. Ich sehe nicht, was im Skript dagegen gemacht werden könnte.

> Bei der Fehlersuche ist mir aufgefallen, dass in Deiner Readme für All-Inkl. noch fehlt:
> `PURGE_AFTER_DAYS=0`
> weil der Befehl zum Löschen auch nicht freigegeben ist.

Danke. Nehme ich noch auf. Würde ich aber gerne anders lösen, als zu sagen "abschalten/nicht verwenden". Wenn ich eine Idee habe, melde ich mich wieder und würde mich freuen, wenn Du mich mit Tests unterstützen könntest.
