### ISSUE TITLE
Tippfehler?

### ISSUE THREAD

**Issue by tschero** [fiedsch/contao-4-backup-script#4]
https://github.com/fiedsch/contao-4-backup-script/blob/0eb5705a17481ea5c5ef6924df7e3e352dcdda36/c4-backup.sh#L196
Hallo fiedsch,
war in dieser Zeile ggf. ein `elseif` gemeint?
Gruß
tschero

**Comment by fiedsch** [comment]
Hallo tschero,

ja, "else if" ist gemeint, aber es heißt in der bash `elif`. Siehe z.B. hier https://linuxacademy.com/blog/linux/conditions-in-bash-scripting-if-statements/

Erzeugt diese Zeile bei Dir einen Fehler?
