### ISSUE TITLE
Alternative Abfrage für uname

### ISSUE THREAD

**Issue by zonky2** [fiedsch/contao-4-backup-script#6]
bei verschiedenen Hostinganbietern wie z.B. Mittwald steht die Abfrage `uname` nicht zur Verfügung - daher kommt es hier 

https://github.com/fiedsch/contao-4-backup-script/blob/master/c4-backup.sh#L191

zu einem Fehler

Gibt es Alternativen dazu?

**Comment by fiedsch** [comment]
Muss ich mir anschauen. Danke für‘s Ticket!

**Comment by zonky2** [comment]
teste gern mit...

**Comment by fiedsch** [comment]
Bin momentan im Urlaub unterwegs. Ich hoffe Anfang Juli etwas zum Testen zu haben.

**Comment by zonky2** [comment]
o.k. - bin auch erst ab 8.07. aus Urlaub zurück bzw. im Büro...

**Comment by fiedsch** [comment]
@zonky2 könntest Du bitte testen, ob das Dein Problem löst? Danke!

**Comment by zonky2** [comment]
mit Angabe von OS geht es
