### ISSUE TITLE
Contao 5

### ISSUE THREAD

**Issue by fiedsch** [fiedsch/contao-4-backup-script#7]
Auch, wenn das Repository `contao-4-backup-script` heißt, sollte es irgendwann für Contao 5 verwendbar sein.

Momentan scheitert das aber (mindestens) an der Bestimmung der Parameter des Datenbankzugangs (die in Contao 5 typischerweise in der `.env*` stehen). 

```
vendor/bin/contao-console debug:container --parameter=database_user
 --------------- ------- 
  Parameter       Value  
 --------------- ------- 
  database_user   null   
 --------------- ------- 
```

**Comment by codesache** [comment]
@fiedsch Kannst du mir sagen, ob das schon im MainScript eingearbeitet bzw. berücksichtigt wird, das die Zugangsdaten in der .env.local stehen und der Ordner /web/ nun /public/ ist.

**Comment by fiedsch** [comment]
Die Verbindung zur Datenbank wird über https://github.com/fiedsch/contao-4-backup-script/blob/bee2cdec975da6a2955af27876a2005e93c17126/c4-backup.sh#L184 geholt. 
Theoretisch sollte es also egal sein, woher Contao die Info dazu hat.
Warum es anscheinend aber trotzdem nicht funktioniert kann ich leider noch nicht sagen.

> und der Ordner /web/ nun /public/ ist.

Das konfigurierst Du hier: 
https://github.com/fiedsch/contao-4-backup-script/blob/bee2cdec975da6a2955af27876a2005e93c17126/main.sh#L71

**Comment by fiedsch** [comment]
```
 bin/console debug:dotenv DATABASE_URL
```
und dann das Ergebnis parsen könnte ein Ansatz sein.

**Comment by fiedsch** [comment]
@codesache Könntest Du bitte Version 2.0.0 probieren? Danke!

**Comment by codesache** [comment]
wo im Serverpfad soll ich bin/console debug:dotenv DATABASE_URL ausführen ?

**Comment by fiedsch** [comment]
Das verwendet Version 2.0 des Backup-Skripts. Du müsstest es updaten (oder neu runterladen) und dann ausführen. Eine angepasste `main.sh` — oder wie auch immer benannt — solltest Du beibehalten können.
